### ISSUE TITLE
Problem with button

### ISSUE THREAD

**Issue by badgerman11** [reven/Light-painter#3]
Hi,
Unfortunately "down" button not working. I've checked wiring and button and everything works properly. 

When compiling I've got this error:

`

C:\Users\ThinkPad\Desktop\student\led\ArduinoUNO\Light-painter-master\Light-painter-master\Light_painter\Light_painter.ino:510:7: warning: extra tokens at end of #else directive

 #else if CONSISTENT

       ^

C:\Users\ThinkPad\Desktop\student\led\ArduinoUNO\Light-painter-master\Light-painter-master\Light_painter\Light_painter.ino: In function 'void getFileName(char*, uint8_t, uint8_t)':

C:\Users\ThinkPad\Desktop\student\led\ArduinoUNO\Light-painter-master\Light-painter-master\Light_painter\Light_painter.ino:610:64: warning: default argument given for parameter 3 of 'void getFileName(char*, uint8_t, uint8_t)' [-fpermissive]

 void getFileName(char* fileName, uint8_t index, uint8_t ext = 0) {

                                                                ^

C:\Users\ThinkPad\Desktop\student\led\ArduinoUNO\Light-painter-master\Light-painter-master\Light_painter\Light_painter.ino:110:6: note: previous specification in 'void getFileName(char*, uint8_t, uint8_t)' here

 void getFileName(char* fileName, uint8_t index, uint8_t ext = 0);

      ^
`

Can you help me?

**Comment by reven** [comment]
Hi,

I'd love to try to help you, but I'll need more clarity on the issue. If the code doesn't compile, how do you know if the button works?

**Comment by reven** [comment]
So I'm closing this issue as no more details have been provided and the issue was ambiguos to begin with.
